import Navbar from './Pages/Navbar.jsx';
import Footer from './Pages/Footer.jsx';
import Home from './Home/Home.jsx';
import SignIn from './Authentication/SignIn.jsx';
import SignUp from './Authentication/SignUp.jsx';
import Contact from './Pages/Contact.jsx';
import Team from './Pages/Team.jsx';
import Error from './Pages/Error.jsx';
import Property from './Home/HostelProperty.jsx';
import Featured from './Home/Featured.jsx';
import ListProperty from './Pages/ListingForms/ListProperty.jsx';
import SearchBar from './Home/SearchBar.jsx';
import Testimonials from './Home/Testimonials/Testimonials.jsx';
import Students from './Pages/ListingForms/Students.jsx';
import Professionals from './Pages/ListingForms/Professionals.jsx';
import PropertyOwner from './Pages/ListingForms/PropertyOwner.jsx';
import ResetPassword from './Authentication/ResetPassword.jsx';
import HostelProperties from './ListProperties/HostelProperties.jsx';
import PGProperties from './ListProperties/PGProperties.jsx';
import FlatProperties from './ListProperties/FlatProperties.jsx';
import HostelProperty from './Home/HostelProperty.jsx';
import FlatProperty from './Home/FlatProperty.jsx';
import PGProperty from './Home/PGProperty.jsx';
import Profile from './Pages/Profile.jsx';

export {Navbar, Footer, Home, SignIn, SignUp, Property, Contact, Team, Error, Featured, ListProperty, SearchBar, Testimonials, Students, Professionals, PropertyOwner, ResetPassword, HostelProperties, PGProperties, FlatProperties, HostelProperty, FlatProperty, PGProperty, Profile};